//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItStock.gettingQuote {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="gettingQuote.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Stockquote", ReplyAction="http://tempuri.org/IService1/StockquoteResponse")]
        string Stockquote(string symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Stockquote", ReplyAction="http://tempuri.org/IService1/StockquoteResponse")]
        System.Threading.Tasks.Task<string> StockquoteAsync(string symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Stocknews", ReplyAction="http://tempuri.org/IService1/StocknewsResponse")]
        string Stocknews(string symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Stocknews", ReplyAction="http://tempuri.org/IService1/StocknewsResponse")]
        System.Threading.Tasks.Task<string> StocknewsAsync(string symbol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItStock.gettingQuote.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItStock.gettingQuote.IService1>, TryItStock.gettingQuote.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Stockquote(string symbol) {
            return base.Channel.Stockquote(symbol);
        }
        
        public System.Threading.Tasks.Task<string> StockquoteAsync(string symbol) {
            return base.Channel.StockquoteAsync(symbol);
        }
        
        public string Stocknews(string symbol) {
            return base.Channel.Stocknews(symbol);
        }
        
        public System.Threading.Tasks.Task<string> StocknewsAsync(string symbol) {
            return base.Channel.StocknewsAsync(symbol);
        }
    }
}
